### ISSUE TITLE
Events for all users

### ISSUE THREAD

**Issue by ruben-burr** [natterstefan/zoom-slack-status-updater#1]
# Question
First of all thanks for these great instructions, they helped a lot! When I create the zoom app as instructed, I get events for all users in the account. Can you give me a hint of what needs to be done to receive only the events for my user?

## Relevant information

Provide as much useful information as you can.

### Your Environment

- Package Version: **x.y.z**

**Comment by natterstefan** [comment]
Hi @ruben-burr,

thanks for the feedback. I'm happy that it is helpful. Let's see.

> I get events for all users in the account.

Have you created the app with a company account or who is "all users"? The account I created the app with is a Basic one (see [Account Types](https://support.zoom.us/hc/en-us/articles/201363173-Account-Types)) and is not connected to a business.

What do you see in the "Activation" tab? That's mine:

![image](https://user-images.githubusercontent.com/1043668/81787919-04ba1a80-9502-11ea-8ef8-4804eb67cc57.png)

**Comment by ruben-burr** [comment]
Hi @natterstefan ,

This is how it looks for me.

![image](https://user-images.githubusercontent.com/1615787/81795493-78612500-950c-11ea-9d89-d4e53e38af8d.png)

The app is created in a company account, yes. All users means all employees of our company. 

Regards, 

Ruben

**Comment by natterstefan** [comment]
According to [Zooms docs](https://marketplace.zoom.us/docs/api-reference/webhook-reference/user-events/presence-status-updated), the response also includes an `account_id`


```
  "event": "user.presence_status_updated",
  "payload": {
    "account_id": "EPjfyjxHMA",
    "object": {
      "date_time": "2019-11-26T20:13:57Z",
      "email": "sfdhfghfgh@dkjdfd.com",
      "id": "z8ycx1223fq",
      "presence_status": "Available"
    }
  }
}
```

I did not account for that right now. We could add this to my [apps configuration](https://github.com/natterstefan/zoom-slack-status-updater#example-configuration) and only react when the account id matches. 🤔

Hopefully, there's an easy way to obtain one's account_id, because you can't from the UI (https://devforum.zoom.us/t/how-to-get-the-account-id-in-the-ui/9742/6).

--

## Tasks

- [ ] add new section in README "how to get one's zoom `account_id`"
- [ ] add new `account_id` filter property in the app configuration
- [ ] update setup section in README
- [ ] test

--

💭 anyway, feel free to submit a PR with a feature for that. I can't afford the time to fix this right now. I'm sorry. :/

**Comment by ruben-burr** [comment]
I would rather go for the email, because it is easier to find out. Will try to put something together in the next days.

**Comment by natterstefan** [comment]
😅 I missed the email and was only looking at the account_id. You are right, make sense! Thank you!
